all: animais profissionais

animais: animais.cpp testa_animais.cpp
	g++ -std=c++11 -Wall animais.cpp testa_animais.cpp -o animais

profissionais: profissionais.cpp testa_profissionais.cpp
	g++ -std=c++11 -Wall profissionais.cpp testa_profissionais.cpp -o profissionais

